[workspace]
resolver = "2"
members = [ 
    "export", 
    "helper",
    "import", 
    "model", 
    "rite", 
    "transform", 
    "plugin", 
    "examples/example_import", 
    "examples/example_export", 
    "examples/example_transform", 
    "plugins/postgres"
]
