[package]
name = "example_transform"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path="../../model" }
transform = { path="../../transform" }
helper = { path="../../helper" }

[lib]
name = "example_transform"
crate-type = ["dylib"]