pub static EMAILS: [&str; 104] = [
    "alice123@example.com",
    "bob.smith@domain.com",
    "charlie_brown@mail.com",
    "diana.prince@example.org",
    "edward.snow@domain.net",
    "frank.underwood@mail.org",
    "grace.hopper@example.com",
    "harry.potter@domain.com",
    "isabella.swan@mail.net",
    "jack.sparrow@example.org",
    "katherine.johnson@domain.com",
    "lara.croft@mail.com",
    "michael.scott@example.net",
    "nancy.drew@domain.org",
    "oliver.twist@mail.com",
    "peter.pan@example.com",
    "quentin.tarantino@domain.net",
    "rachel.green@mail.org",
    "sam.wise@example.com",
    "taylor.swift@domain.com",
    "ursula.le_guin@mail.net",
    "violet.beauregarde@example.org",
    "walter.white@domain.com",
    "xena.warrior@mail.com",
    "yoda.jedi@example.net",
    "zoe.washburne@domain.org",
    "alex.trebek@mail.com",
    "barack.obama@example.com",
    "chris.evans@domain.net",
    "daisy.ridley@mail.org",
    "elon.musk@example.com",
    "finn.the_human@domain.com",
    "gandalf.grey@mail.net",
    "hannah.baker@example.org",
    "ian.fleming@domain.com",
    "jane.austen@mail.com",
    "kermit.frog@example.net",
    "leonardo.dicaprio@domain.org",
    "marie.curie@mail.net",
    "neil.armstrong@example.com",
    "oprah.winfrey@domain.com",
    "pablo.picasso@mail.org",
    "queen.elizabeth@example.net",
    "robert.downey@domain.org",
    "scarlett.johansson@mail.com",
    "thomas.edison@example.com",
    "ursula.k_le_guin@domain.net",
    "vince.vaughn@mail.org",
    "walter.cronkite@example.com",
    "xavier.woods@domain.com",
    "yogi.bear@mail.net",
    "zach.galifianakis@example.org",
    "albert.einstein@domain.com",
    "bill.gates@mail.com",
    "charlie.chaplin@example.net",
    "dolly.parton@domain.org",
    "elvis.presley@mail.net",
    "freddie.mercury@example.com",
    "george.clooney@domain.com",
    "harrison.ford@mail.org",
    "indiana.jones@example.net",
    "jennifer.lopez@domain.org",
    "keanu.reeves@mail.com",
    "lady.gaga@example.com",
    "matt.damon@domain.net",
    "nicolas.cage@mail.org",
    "olivia.newton_john@example.com",
    "paul.mccartney@domain.com",
    "quincy.jones@mail.net",
    "rachel.mcadams@example.org",
    "sean.connery@domain.com",
    "tom.hanks@mail.com",
    "ursula.andress@example.net",
    "viggo.mortensen@domain.org",
    "walter.matthau@mail.com",
    "xander.cage@example.com",
    "yara.shahidi@domain.net",
    "zendaya.coleman@mail.org",
    "alicia.keys@example.com",
    "brad.pitt@domain.com",
    "chris.hemsworth@mail.net",
    "dwayne.johnson@example.org",
    "emma.watson@domain.com",
    "florence.nightingale@mail.com",
    "gal.gadot@example.net",
    "halle.berry@domain.org",
    "ida.b_wells@mail.net",
    "james.bond@example.com",
    "kamala.harris@domain.com",
    "leonardo.da_vinci@mail.org",
    "margaret.thatcher@example.net",
    "nelson.mandela@domain.org",
    "oprah.w@mail.com",
    "prince.harry@example.com",
    "queen.latifah@domain.com",
    "ruth.bader_ginsburg@mail.net",
    "serena.williams@example.org",
    "tiger.woods@domain.com",
    "ursula.von_der_leyen@mail.com",
    "vladimir.putin@example.net",
    "will.smith@domain.org",
    "xavier.naidoo@mail.com",
    "yasser.arafat@example.com",
    "zinedine.zidane@domain.com",
];

// Define a public static array of cities in Germany
pub static GERMAN_CITIES: [&str; 95] = [
    "Berlin",
    "Hamburg",
    "Munich",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    "Essen",
    "Leipzig",
    "Bremen",
    "Dresden",
    "Hanover",
    "Nuremberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Mannheim",
    "Karlsruhe",
    "Wiesbaden",
    "Münster",
    "Gelsenkirchen",
    "Augsburg",
    "Mönchengladbach",
    "Aachen",
    "Kiel",
    "Halle (Saale)",
    "Magdeburg",
    "Freiburg im Breisgau",
    "Krefeld",
    "Lübeck",
    "Oberhausen",
    "Mainz",
    "Erfurt",
    "Rostock",
    "Kassel",
    "Hagen",
    "Saarbrücken",
    "Hamm",
    "Herne",
    "Mülheim an der Ruhr",
    "Potsdam",
    "Ludwigshafen am Rhein",
    "Oldenburg",
    "Leverkusen",
    "Osnabrück",
    "Solingen",
    "Heidelberg",
    "Neuss",
    "Darmstadt",
    "Paderborn",
    "Regensburg",
    "Ingolstadt",
    "Würzburg",
    "Fürth",
    "Wolfsburg",
    "Ulm",
    "Heilbronn",
    "Pforzheim",
    "Göttingen",
    "Bottrop",
    "Trier",
    "Recklinghausen",
    "Reutlingen",
    "Bremerhaven",
    "Koblenz",
    "Bergisch Gladbach",
    "Jena",
    "Remscheid",
    "Erlangen",
    "Moers",
    "Siegen",
    "Hildesheim",
    "Salzgitter",
    "Cottbus",
    "Kaiserslautern",
    "Gütersloh",
    "Witten",
    "Schwerin",
    "Iserlohn",
    "Ludwigsburg",
    "Gera",
    "Tübingen",
    "Zwickau",
    "Düren",
    "Ratingen",
    "Lünen",
    "Marl",
    "Velbert",
    "Minden",
    "Wilhelmshaven",
    "Villingen-Schwenningen",
    "Konstanz",
];

pub static LAST_NAMES: [&str; 130] = [
    // German Last Names (70%)
    "Müller",
    "Schmidt",
    "Schneider",
    "Fischer",
    "Weber",
    "Meyer",
    "Wagner",
    "Becker",
    "Schulz",
    "Hoffmann",
    "Schäfer",
    "Koch",
    "Bauer",
    "Richter",
    "Klein",
    "Wolf",
    "Schröder",
    "Neumann",
    "Zimmermann",
    "Braun",
    "Krüger",
    "Hofmann",
    "Hartmann",
    "Lange",
    "Schwarz",
    "Schmitt",
    "Werner",
    "Schmitz",
    "Krause",
    "Meier",
    "Lehmann",
    "Schmid",
    "Weiss",
    "Fuchs",
    "Schubert",
    "Köhler",
    "Keller",
    "Vogel",
    "Jung",
    "Herrmann",
    "Kaiser",
    "Maier",
    "Schreiber",
    "Frank",
    "Zimmer",
    "Beck",
    "Eckert",
    "Bergmann",
    "Walter",
    "Stein",
    "Lang",
    "Scholz",
    "Winkler",
    "Roth",
    "Kern",
    "Lorenz",
    "Heinrich",
    "Kurz",
    "Böhm",
    "Mayer",
    "Schulze",
    "König",
    "Bauer",
    "Graf",
    "Dietrich",
    "Berger",
    "Friedrich",
    "Hahn",
    "Kruse",
    "Horn",
    "Busch",
    "Seidel",
    "Simon",
    "Haas",
    "Winter",
    "Jäger",
    "Kraus",
    "Steiner",
    "Peters",
    "Otto",
    "Sommer",
    "Günther",
    "Schuster",
    "Albrecht",
    "Schilling",
    "Kuhn",
    "Brandt",
    "Schramm",
    "Schumacher",
    "Riedel",
    "Götz",
    "Thiele",
    "Schindler",
    "Franke",
    "Beyer",
    "Kühn",
    "Hübner",
    "Reinhardt",
    "Voigt",
    "Fritz",
    "Barth",
    "Schindler",
    "Vogt",
    "Engel",
    "Krebs",
    // International Last Names (30%)
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
];

pub static FIRST_NAMES: [&str; 100] = [
    // German First Names (70%)
    "Max",
    "Anna",
    "Paul",
    "Laura",
    "Lukas",
    "Lea",
    "Jonas",
    "Emma",
    "Elias",
    "Hannah",
    "Ben",
    "Lena",
    "Finn",
    "Mia",
    "Noah",
    "Sophia",
    "Leon",
    "Emilia",
    "Luca",
    "Marie",
    "Felix",
    "Lina",
    "David",
    "Jana",
    "Julian",
    "Sarah",
    "Niklas",
    "Lisa",
    "Tim",
    "Charlotte",
    "Lars",
    "Katharina",
    "Jan",
    "Julia",
    "Moritz",
    "Lara",
    "Simon",
    "Lilly",
    "Tobias",
    "Luisa",
    "Philipp",
    "Clara",
    "Alexander",
    "Nina",
    "Jakob",
    "Maria",
    "Maximilian",
    "Sofia",
    "Henry",
    "Amelie",
    "Leo",
    "Ella",
    "Oskar",
    "Milena",
    "Anton",
    "Lotta",
    "Vincent",
    "Helena",
    "Theo",
    "Emily",
    "Johannes",
    "Alina",
    "Erik",
    "Rosa",
    "Fabian",
    "Stella",
    "Matteo",
    "Greta",
    "Liam",
    "Victoria",
    // International First Names (30%)
    "James",
    "Olivia",
    "Liam",
    "Emma",
    "William",
    "Ava",
    "Oliver",
    "Sophia",
    "Elijah",
    "Isabella",
    "Lucas",
    "Charlotte",
    "Mason",
    "Amelia",
    "Ethan",
    "Mia",
    "Alexander",
    "Harper",
    "Henry",
    "Evelyn",
    "Jacob",
    "Abigail",
    "Michael",
    "Emily",
    "Daniel",
    "Ella",
    "Logan",
    "Elizabeth",
    "Jackson",
    "Sofia",
];

pub static STREET_ADDRESSES: [&str; 70] = [
    "Musterstraße 12",
    "Beispielweg 45",
    "Hauptstraße 78",
    "Nebenstraße 34",
    "Blumenweg 67",
    "Lindenallee 23",
    "Kirchplatz 56",
    "Marktplatz 89",
    "Bahnhofstraße 123",
    "Rathausplatz 456",
    "Schlossallee 789",
    "Parkstraße 101",
    "Waldweg 202",
    "Feldstraße 303",
    "Seeufer 404",
    "Bergstraße 505",
    "Talweg 606",
    "Flussstraße 707",
    "Brückenweg 808",
    "Hafenstraße 909",
    "Amselweg 110",
    "Eichenstraße 211",
    "Birkenallee 312",
    "Tannenweg 413",
    "Kiefernstraße 514",
    "Buchenweg 615",
    "Ahornstraße 716",
    "Eschenweg 817",
    "Ulmenstraße 918",
    "Lärchenweg 109",
    "Rosenstraße 120",
    "Nelkenweg 221",
    "Tulpenstraße 322",
    "Sonnenblumenweg 423",
    "Margeritenstraße 524",
    "Veilchenweg 625",
    "Gartenstraße 726",
    "Wiesenweg 827",
    "Feldblumenstraße 928",
    "Blütenweg 139",
    "Erlenstraße 140",
    "Weidenweg 241",
    "Pappelallee 342",
    "Kastanienstraße 443",
    "Eschenallee 544",
    "Akazienweg 645",
    "Magnolienstraße 746",
    "Jasminweg 847",
    "Fliederstraße 948",
    "Kirschblütenstraße 159",
    "Apfelbaumstraße 160",
    "Birnenweg 261",
    "Pflaumenallee 362",
    "Kastanienallee 463",
    "Eichenallee 564",
    "Buchenallee 665",
    "Ahornallee 766",
    "Eschenallee 867",
    "Ulmenallee 968",
    "Lärchenallee 179",
    "Rosenallee 180",
    "Nelkenallee 281",
    "Tulpenallee 382",
    "Sonnenblumenallee 483",
    "Margeritenallee 584",
    "Veilchenallee 685",
    "Gartenallee 786",
    "Wiesenallee 887",
    "Feldblumenallee 988",
    "Blütenallee 299",
];


pub static STATES_PROVINCES: [&str; 102] = [
    // Germany (16 states)
    "Baden-Württemberg",
    "Bavaria",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse",
    "Lower Saxony",
    "Mecklenburg-Western Pomerania",
    "North Rhine-Westphalia",
    "Rhineland-Palatinate",
    "Saarland",
    "Saxony",
    "Saxony-Anhalt",
    "Schleswig-Holstein",
    "Thuringia",
    
    // United States (50 states)
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",

    // Canadian provinces and territories (13)
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon",

    // Australian states and territories (8)
    "Australian Capital Territory",
    "New South Wales",
    "Northern Territory",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia",

    // Major Mexican states (15 selected)
    "Baja California",
    "Chihuahua",
    "Coahuila",
    "Guadalajara",
    "Guanajuato",
    "Jalisco",
    "Mexico City",
    "Monterrey",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Quintana Roo",
    "Sinaloa",
    "Sonora",
    "Yucatán"
];