name: "Build image"
description: "Builds a container image"
inputs:
  image_name: 
    description: "The name of the image to be built"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.ORG_GITHUB_PAT }}

    - name: Login container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ inputs.image_name }}"

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GRPC_UTILS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Download base image artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.image_name }}"
        path: /tmp

    - name: Load base image
      run: docker load -i /tmp/base.tar

    - name: Build and push container image
      uses: docker/build-push-action@v4
      id: build-and-push
      with:
        context: .
        file: ./Dockerfile.extended
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        ssh: default
        outputs: |
            type=docker,dest=/tmp/extended.tar

    - name: Save extended image artifact
      uses: actions/upload-artifact@v4
      with:
        name: rite-extended
        path: /tmp/extended.tar
