[package]
name = "rite"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path="../model" }
helper = { path="../helper" }
plugin = { path="../plugin" }
import = { path="../import" }
export = { path="../export" }
transform = { path="../transform" }
gag = "1.0"
log = "0.4"
log4rs = "1.3"
moka = {version="0.12", features = ["sync"]}
clap = { version= "4.5", features = ["derive"] }
