[package]
name = "rite"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path="../model" }
helper = { path="../helper" }
plugin = { path="../plugin" }
import = { path="../import" }
export = { path="../export" }
transform = { path="../transform" }
gag = "1.0.0"
log = "0.4.22"
log4rs = "1.3.0"

