[package]
name = "rite"
version = "0.1.2"
edition = "2021"
description = "RITE - rust import/transform/export"
readme = "README.md"
repository = "https://github.com/CIAO-systems/rite"
license = "Apache-2.0"

[dependencies]
model = { version="0.1", path="../../libraries/model" }
helper = { version="0.1.0", path="../../libraries/helper" }
plugin = { version="0.1.0", path="../../libraries/plugin" }
import = { version="0.1.0", path="../../libraries/import" }
export = { version="0.1.0", path="../../libraries/export" }
transform = { version="0.1.0", path="../../libraries/transform" }
gag = "1.0"
log = "0.4"
log4rs = "1.3"
moka = {version="0.12", features = ["sync"]}
clap = { version= "4.5", features = ["derive"] }
dotenv = "0.15.0"
colored = "3.0.0"
