#!/bin/env bash
cargo tarpaulin \
    --skip-clean --locked \
    --all-features \
    --workspace \
    --timeout 300 \
    --exclude-files "base/rite/src/main.rs" \
    --exclude-files "base/rite/src/processor/process.rs" \
    --exclude-files "base/plugins/llm/src/importers/**" \
    --exclude-files "extended/plugins/personio/src/importers/absences/importer.rs" \
    --exclude-files "extended/plugins/personio/src/importers/absences/initializable.rs" \
    --exclude-files "extended/plugins/personio/src/importers/attendances/importer.rs" \
    --exclude-files "extended/plugins/personio/src/importers/attendances/initializable.rs" \
    --exclude-files "extended/plugins/personio/src/importers/employees/importer.rs" \
    --exclude-files "extended/plugins/personio/src/importers/employees/initializable.rs" \
    --exclude-files "extended/plugins/personio/src/importers/projects/importer.rs" \
    --exclude-files "extended/plugins/personio/src/importers/projects/initializable.rs" \
    --exclude-files "custom/target/**" \
    --exclude-files "custom/plugins/ciao/ciao-rs/**" \
    --exclude-files "custom/plugins/atc/bin/**" \
    --exclude-files "custom/plugins/atc/src/connection/clients/manager/tests/**" \
    --out Html \
    --output-dir target/coverage
