#!/bin/env bash
cargo tarpaulin \
    --skip-clean --locked \
    --all-features \
    --workspace \
    --timeout 300 \
    --exclude-files "base/rite/src/main.rs" \
    --exclude-files "base/rite/src/processor/process.rs" \
    --exclude-files "base/plugins/llm/src/importers/**" \
    --exclude-files "base/plugins/mariadb/src/exporter.rs" \
    --exclude-files "base/plugins/mariadb/src/exporter/tests.rs" \
    --exclude-files "extended/plugins/personio/src/importers/absences/importer.rs" \
    --exclude-files "extended/plugins/personio/src/importers/absences/initializable.rs" \
    --exclude-files "extended/plugins/personio/src/importers/attendances/importer.rs" \
    --exclude-files "extended/plugins/personio/src/importers/attendances/initializable.rs" \
    --exclude-files "extended/plugins/personio/src/importers/employees/importer.rs" \
    --exclude-files "extended/plugins/personio/src/importers/employees/initializable.rs" \
    --exclude-files "extended/plugins/personio/src/importers/projects/importer.rs" \
    --exclude-files "extended/plugins/personio/src/importers/projects/initializable.rs" \
    --out Html \
    --out Xml \
    --output-dir target/coverage
