[package]
name = "transform"
version = "0.1.0"
edition = "2021"
description = "RITE transformer trait"
readme = "README.md"
repository = "https://github.com/CIAO-systems/rite"
license = "Apache-2.0"
publish = ["kellnr"]

[dependencies]
model = { version="0.1", registry="kellnr", path="../model" }
