[workspace]
resolver = "2"
members = [ 
    "rite", 
    "plugins/common", 
    "plugins/postgres", 
    "plugins/mariadb", 
    "plugins/rest", 
    "plugins/faker", 
    "plugins/csv", 
    "plugins/llm", 
]
