name: Build Docker Images

on:
    workflow_dispatch:
    push:
        branches: [ "main" ] 
    pull_request:
        branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BASE: ${{ github.repository }}-base
  IMAGE_NAME_EXTENDED: ${{ github.repository }}-extended
  IMAGE_NAME_CUSTOM: ${{ github.repository }}-custom

jobs:
    build_base:
        name: Build Base Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.ORG_GITHUB_PAT }}

            - name: Login container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}
        
            - name: Set up SSH agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GRPC_UTILS }}
        
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
                
            - name: Build and push container image
              uses: docker/build-push-action@v4
              id: build-and-push
              with:
                context: .
                file: ./Dockerfile.base
                push: false
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                ssh: default
                outputs: |
                    type=docker,dest=/tmp/base.tar

            - name: Save base image artifact
              uses: actions/upload-artifact@v4
              with:
                name: rite-base
                path: /tmp/base.tar

    build_extended:
        name: Build Extended Image
        needs: build_base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.ORG_GITHUB_PAT }}

            - name: Login container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_EXTENDED }}
        
            - name: Set up SSH agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GRPC_UTILS }}
        
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
                
            - name: Download base image artifact
              uses: actions/download-artifact@v4
              with:
                name: rite-base
                path: /tmp

            - name: Load base image
              run: docker load -i /tmp/base.tar

            - name: Build and push container image
              uses: docker/build-push-action@v4
              id: build-and-push
              with:
                context: .
                file: ./Dockerfile.extended
                push: false
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                ssh: default
                outputs: |
                    type=docker,dest=/tmp/extended.tar

            - name: Save extended image artifact
              uses: actions/upload-artifact@v4
              with:
                name: rite-extended
                path: /tmp/extended.tar

    build_custom:
        name: Build Custom Image
        needs: build_extended
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.ORG_GITHUB_PAT }}

            - name: Login container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CUSTOM }}
        
            - name: Set up SSH agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GRPC_UTILS }}
        
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
                
            - name: Download extended artifact
              uses: actions/download-artifact@v4
              with:
                name: rite-extended
                path: /tmp

            - name: Load extended image
              run: docker load -i /tmp/extended.tar

            - name: Build and push container image
              uses: docker/build-push-action@v4
              id: build-and-push
              with:
                context: .
                file: ./Dockerfile.custom
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                ssh: default
