name: Build Docker Images

on:
    workflow_dispatch:
    push:
        branches: [ "main" ] 
    pull_request:
        branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_TAG: main
  IMAGE_NAME_BASE: ${{ github.repository }}-base
  IMAGE_NAME_EXTENDED: ${{ github.repository }}-extended
  IMAGE_NAME_CUSTOM: ${{ github.repository }}-custom

permissions:
  packages: write
  contents: read

jobs:
    build_base:
        if: false
        name: Build Base Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.ORG_GITHUB_PAT }}

            - name: Login container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}
        
            - name: Set up SSH agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GRPC_UTILS }}
        
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
                
            - name: Build and push container image
              uses: docker/build-push-action@v4
              id: build-and-push
              with:
                context: .
                file: ./Dockerfile.base
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                ssh: default

    build_extended:
        name: Build Extended Image
        needs: build_base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.ORG_GITHUB_PAT }}

            - name: Login container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_EXTENDED }}
        
            - name: Set up SSH agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GRPC_UTILS }}
        
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
                
            - name: Set base image tag
              id: set_base_image_tag
              run: |
                if [[ ${{ github.event_name }} == 'pull_request' ]]; then
                  # For pull requests: "pr-NUMBER"
                  echo "BASE_IMAGE_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
                else
                  # For pushes to branches (including main)
                  echo "BASE_IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
                fi

            - name: Build and push container image
              uses: docker/build-push-action@v4
              id: build-and-push
              with:
                context: .
                file: ./Dockerfile.extended
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                ssh: default
                build-args: |
                  BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}

    build_custom:
        name: Build Custom Image
        needs: build_extended
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.ORG_GITHUB_PAT }}

            - name: Login container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CUSTOM }}
        
            - name: Set up SSH agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GRPC_UTILS }}
        
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
                
            - name: Build and push container image
              uses: docker/build-push-action@v4
              id: build-and-push
              with:
                context: .
                file: ./Dockerfile.custom
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                ssh: default
